### ISSUE TITLE
Command error in README.md

### ISSUE THREAD

**Issue by jianingwang123** [Azure-Samples/nlp-sql-in-a-box#6]
**Describe the issue:**
In the [README.md](https://github.com/Azure-Samples/nlp-sql-in-a-box?tab=readme-ov-file#azd-deploy), the cloned repository name is wrong as follows. It is recommended to use the `azd init` command to clone the repository:

![image](https://github.com/user-attachments/assets/d779947b-511a-48ea-a5c6-850e475094fe)

**Suggestion:**
Update to `azd init --template Azure-Samples/nlp-sql-in-a-box`.

@hemarina and @codebytes for notification.

**Comment by jianingwang123** [comment]
The [PR](https://github.com/Azure-Samples/nlp-sql-in-a-box/pull/5) is fixing the current issue, when the PR is merged, we will also close this issue.

**Comment by codebytes** [comment]
merged, thank you
