### ISSUE TITLE
Failed to run command `python -m src.app` when running locally

### ISSUE THREAD

**Issue by jianingwang123** [Azure-Samples/nlp-sql-in-a-box#7]
**Describe the issue:**
According to [README.md](https://github.com/Azure-Samples/nlp-sql-in-a-box/blob/main/README.md), when running the command `python -m src.app`, encountered an error:

![image](https://github.com/user-attachments/assets/048f0be8-6614-428e-b8c8-1e46ce43b074)

**Repro Steps:**

1. Clone this repository locally.
2. Run `az login`.
3. Run `azd auth login`.
4. Find out IPv4 address and run `azd env set IP_ADDRESS <ip_address>`.
5. Run `azd up`.
6. Run `pip install -r src/requirements.txt`.
7. Run `python -m src.app`.

**Environment:**

- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Windows

**Expected behavior:**
Success to run locally.

@hemarina and @codebytes for notification.

**Comment by codebytes** [comment]
reviewing. @franklinlindemberg  can you also verify?

**Comment by franklinlindemberg** [comment]
hey @jianingwang123, I noticed in your error message an auth error when connecting to speech services.

- Do you have the envs set in the .env in the root folder?
- Is it possible that you were not logged in into az when you ran this code? The `credential = DefaultAzureCredential()` command would be responsible for picking in az account and creating tokens to authenticate to services
- Could you change your log level to debug line 20 in `app.py`, run again and check if it gives any useful information?

**Comment by codebytes** [comment]
@franklinlindemberg  i just ran through the steps again. at the azd up step its still prompting for principleid
![image](https://github.com/user-attachments/assets/90f3651f-daf9-4e49-86ee-96c632e01cdc)

**Comment by franklinlindemberg** [comment]
@codebytes does that happen only the first time you run or in following ones as well?

Im wondering if it would be better to remove the principalId from the hook in azure.yaml and ask the user to manually set this as an env var (similar to the IP one). what do you think?

**Comment by codebytes** [comment]
i think i see issue, with hooks. one sec

**Comment by jianingwang123** [comment]
@codebytes and @franklinlindemberg, based on the latest code tested, the same error still exists, running the command `python -m src.app` again will result in the following error. After we add the IPv4 address to the SQL Service and Speech Services according to the error prompt, the test ran successfully.
We got the IPv4 address from https://www.whatismyip.com/, which is different from the IPv4 address in the error message, so we encounter this issue. Could you please tell us how to find the correct IPv4 address and add the way to the Readme.md?
![image](https://github.com/user-attachments/assets/3a3ace66-237d-41cb-b1d7-88c4d740deca)

**Comment by franklinlindemberg** [comment]
@jianingwang123 I just checked https://www.whatismyip.com/ and it shows the same IP that I used in the service, so I would expect that to work

Are you running this code in your local machine directly? Is it possible that your browser is using a different network than your code?

I also tested this command in windows and it showed the same up, can you validate on your side what it shows? (tested in windows)
`nslookup myip.opendns.com resolver1.opendns.com`

**Comment by codebytes** [comment]
@jianingwang123  I had some weird behavior when i kept doing azd up and running the sample.
After code changes. I made an entirely new environment and started from scratch. Then tested, I didn't see error then.
Also can you validate that your ipaddress that you are setting is the ip address accessing azure services? (If you are coming over a vpn or private ip)

**Comment by jianingwang123** [comment]
@franklinlindemberg and @codebytes We run this code directly on the local machine. When I connect to the VPN test, my IPv4 address is inconsistent with the IPv4 address accessing azure services, and encounter this issue. 
However, when I disconnect the VPN, my IPv4 address is consistent with the IPv4 address accessing azure services, and the test passes.
