### ISSUE TITLE
[Option] Publish to azure sample browser

### ISSUE THREAD

**Issue by hemarina** [Azure-Samples/nlp-sql-in-a-box#9]
This repository is added to [awesome-azd](aka.ms/awesome-azd) site and it is a Microsoft-authored template, we encourage you to [publish it to learn.microsoft.com/samples](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main) if you are interested.

I saw the metadata in Readme but is not able to search the template in [azure sample browser](https://learn.microsoft.com/en-us/samples/browse/?filter-products=nlp-sql-in-a-box&terms=NLP%20to%20SQL%20Chatbot). Since this repo is not showing in [samples](https://github.com/MicrosoftDocs/samples/tree/main/Azure-Samples), I assume [onboarding form](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main#complete-onboarding-form) needs to be completed.

**Comment by codebytes** [comment]
Submitted form, thank you!
